### ISSUE TITLE
ENABLE_TLS_REVERSE_PROXY option doesn't work with HTTP

### ISSUE THREAD

**Issue by ryukenji3** [tiredofit/docker-libreoffice-online#11]
Hello Tiredofit,

As you mentioned in #4 ,you added a tonne more configuration options  for the configuration file to avoid having to use the EXTRA PARAMETERS option.

when use HTTP, I should set the 2 option to FALSE as you said, but this does not change the prefix of the IP in ipaddress:9980/hosting/discovery, it is still HTTPS, 

<img width="850" alt="image" src="https://user-images.githubusercontent.com/76910583/103523742-4e071200-4eb7-11eb-9caa-7d9527dc0ea5.png">

which is not working in HTTP environment, still need to add '- EXTRA_OPTIONS'parameters to make the prefix HTTP.

- ENABLE_TLS=FALSE
- ENABLE_TLS_REVERSE_PROXY=FALSE
- EXTRA_OPTIONS=--o:ssl.enable=false --o:ssl.termination=false

**Comment by tiredofit** [comment]
Hi thanks for the report. 
I've just released a new version of this image (`2.0.0`) which should resolve this., Can you let me know if fixed?

**Comment by ryukenji3** [comment]
Hi, thanks for the release!
Just tested but failed with start error : 

```
[NOTICE] ** [libreoffice-online] Autogenerating Configuration File

sed: -e expression #1, char 107: invalid reference \1 on `s' command's RHS

Setting up watches.

Watches established.

[cont-init.d] 10-loolwsd: exited 0.

[cont-init.d] 99-container: executing...

[cont-init.d] 99-container: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[INFO] ** [zabbix] Starting Zabbix Agent

[INFO] ** [libreoffice-online] Starting Libreoffice Online Web Services daemon

./run: line 14: /var/log/lool/loolwsd.log: No such file or directory
```

Which "./run: line 14: /var/log/lool/loolwsd.log: No such file or directory" keeps looping.

**Comment by tiredofit** [comment]
That's embarrassing. I think I've uploaded the wrong release. Removing from Docker Hub :)
Hang tight. Going to take me a couple hours to recompile this.

**Comment by tiredofit** [comment]
Can you try `tiredofit/libreoffice-online:develop` ?

I'm compiling ok but I can't seem to connect properly from a nextcloud system. Wanting to know if you see the same.
ENABLE_TLS is FALSE and ENABLE_TLS_REVERSE_PROXY=TRUE in this image by default.

**Comment by ryukenji3** [comment]
Extremely slow when pulling this tag, has been stucked at ```33b57562e40d: Downloading  387.2MB/2.622GB```  for 30min. Will try this later.

**Comment by tiredofit** [comment]
OK. :develop :latest and :2.0.0 are the exact same tag at the moment. I believe it is fixed. I'm not sure why the image size exploded. I did have to change the way Libreoffice was compiled to get 6.4 to work.

**Comment by ryukenji3** [comment]
Got it work with Nextcloud , but go back to the option ```ENABLE_TLS_REVERSE_PROXY``` seems not working at all. Here's the conclusion after several test:

set ```ENABLE_TLS=TRUE```, -> got libreoffice-online running in **HTTPS** and the prefix in /hosting/discovery is also **HTTPS**; (no matter ```ENABLE_TLS_REVERSE_PROXY``` is set to TRUE or FALSE);

set ```ENABLE_TLS=FALSE```, -> got libreoffice-online running in **HTTP** and the prefix in /hosting/discovery is also **HTTP**; (no matter ```ENABLE_TLS_REVERSE_PROXY``` is set to TRUE or FALSE, the prefix is always in HTTP)

**Comment by tiredofit** [comment]
Thanks for the report. I'll look into this and sort this once and for all. I had a different way of doing the configuration files in a previous dev incarnation and then it just started throwing segfaults when I was about to finalize the image. I also have mine working in a Nextcloud environment, but want to make sure that all the options are working.

**Comment by tiredofit** [comment]
Ha - After all of that. Now we have a `2.0.1` which will fix the TLS issues once and for all (famous last words). 

Nice part about it is that we get an easily updateable image to match version parity with the releases. 
Hope this solves this issue once and for all :)

**Comment by ryukenji3** [comment]
Working like a charm!  But somehow the image soared to 7.34GB...

**Comment by tiredofit** [comment]
It's pretty much a mystery to me how it grew so much. 
There are some monster files for libreoffice compiled now, I will have to compare with the "official" code image and see if they match up.

````
  1.4 GiB [##########]  libmergedlo.so
  628.6 MiB [####      ]  libsclo.so
  582.8 MiB [####      ]  libswlo.so
  197.2 MiB [#         ]  libsdlo.so
  158.6 MiB [#         ]  libscfiltlo.so
  131.6 MiB [          ]  libooxlo.so
  119.5 MiB [          ] /resource
  102.5 MiB [          ]  libdbulo.so
````

Also, I'm including more dictionaries, perhaps I should pare back:

````
   81.7 MiB [##########] /dict-de
   24.6 MiB [###       ] /dict-en
   11.5 MiB [#         ] /dict-pt-BR
   11.1 MiB [#         ] /dict-no
   10.8 MiB [#         ] /dict-sr
   10.0 MiB [#         ] /dict-gl
    9.7 MiB [#         ] /dict-el
    8.9 MiB [#         ] /dict-tr
    7.7 MiB [          ] /dict-ar
````
