### ISSUE TITLE
server name is hash

### ISSUE THREAD

**Issue by hmt** [tiredofit/docker-libreoffice-online#12]
I've set up your docker image as a vpath along my nextcloud vhost:

```
nextcloud.domain.com
nextcloud.domain.com/lool
```

It seems to work because I can reach the admin console (slightly messed up because of l10 error messages but nontheless)
However, the url that I set to forward all my requests are turned into the hash that is stored in `/etc/loolwsd/loolwsd.xml` under `<server_name>`. So all requests fail and look like this: `https://b40e55c32789/loleaflet/44a46d78c/loleaflet.html?WOPISrc=https%3A%2F%2.......`

**Comment by adroslice** [comment]
I'm having the same issue.

**Comment by adroslice** [comment]
It's worth noting that, with no persistent storage set up, this hash changes on every restart.
This hash-as-host problem shows up in server-domain/hosting/discovery, proving that it's a problem with the container.
When I attempted a manual install based on the commands listed in the dockerfile *before* I grabbed the docker image itself, I did not have this problem.

**Comment by adroslice** [comment]
I've just confirmed that it's indeed the container ID.

**Comment by tiredofit** [comment]
I just updated the examples folder with a way to make your hsotname not be the container hash.

In short just add `hostname: libreoffice.example.com` and it will relay the proper address going forward :)

**Comment by adroslice** [comment]
Thanks a lot, that resolves the issue for me.
