### ISSUE TITLE
Got log cycle

### ISSUE THREAD

**Issue by whlsxl** [tiredofit/docker-libreoffice-online#4]
After set - "DONT_GEN_SSL_CERT=true" & - "extra_params=--o:ssl.enable=false"
still got this error

> wsd-01186-01186 2019-07-06 17:16:20.022850 [ loolwsd ] INF  Adding trusted WOPI host: [{nextcloud_URL}].| wsd/Storage.cpp:106
> wsd-01186-01186 2019-07-06 17:16:20.022865 [ loolwsd ] INF  Adding trusted WOPI host: [10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}].| wsd/Storage.cpp:106
> wsd-01186-01186 2019-07-06 17:16:20.022876 [ loolwsd ] INF  Adding trusted WOPI host: [172\.1[6789]\.[0-9]{1,3}\.[0-9]{1,3}].| wsd/Storage.cpp:106
> wsd-01186-01186 2019-07-06 17:16:20.022887 [ loolwsd ] INF  Adding trusted WOPI host: [172\.2[0-9]\.[0-9]{1,3}\.[0-9]{1,3}].| wsd/Storage.cpp:106
> wsd-01186-01186 2019-07-06 17:16:20.022898 [ loolwsd ] INF  Adding trusted WOPI host: [172\.3[01]\.[0-9]{1,3}\.[0-9]{1,3}].| wsd/Storage.cpp:106
> wsd-01186-01186 2019-07-06 17:16:20.022909 [ loolwsd ] INF  Adding trusted WOPI host: [192\.168\.[0-9]{1,3}\.[0-9]{1,3}].| wsd/Storage.cpp:106
> wsd-01186-01186 2019-07-06 17:16:20.022918 [ loolwsd ] INF  Adding blocked WOPI host: [192\.168\.1\.1].| wsd/Storage.cpp:111
> wsd-01186-01186 2019-07-06 17:16:20.023330 [ loolwsd ] INF  AdminModel ctor.| wsd/AdminModel.hpp:212
> wsd-01186-01186 2019-07-06 17:16:20.023342 [ loolwsd ] INF  Admin ctor.| wsd/Admin.cpp:362
> wsd-01186-01186 2019-07-06 17:16:20.023518 [ loolwsd ] TRC  Total system memory:  7786852 KB.| wsd/Admin.cpp:365
> wsd-01186-01186 2019-07-06 17:16:20.023665 [ loolwsd ] TRC  Total available memory: 6229481 KB (memproportion: 80%).| wsd/Admin.cpp:372
> wsd-01186-01186 2019-07-06 17:16:20.024595 [ loolwsd ] TRC  Total memory used: 17373 KB.| wsd/Admin.cpp:375
> wsd-01186-01186 2019-07-06 17:16:20.024653 [ loolwsd ] INF  Loolwsd version details: 4.0.4 - a2132266| wsd/LOOLWSD.cpp:3090
> wsd-01186-01186 2019-07-06 17:16:20.024667 [ loolwsd ] INF  SSL Cert file: /etc/loolwsd/cert.pem| wsd/LOOLWSD.cpp:1176
> wsd-01186-01186 2019-07-06 17:16:20.024676 [ loolwsd ] INF  SSL Key file: /etc/loolwsd/key.pem| wsd/LOOLWSD.cpp:1179
> wsd-01186-01186 2019-07-06 17:16:20.024685 [ loolwsd ] INF  SSL CA file: /etc/loolwsd/ca-chain.cert.pem| wsd/LOOLWSD.cpp:1182
> wsd-01186-01186 2019-07-06 17:16:20.024691 [ loolwsd ] INF  SSL Cipher list: | wsd/LOOLWSD.cpp:1185
> wsd-01186-01186 2019-07-06 17:16:20.024886 [ loolwsd ] FTL  Cannot load CA file/directory at /etc/loolwsd/ca-chain.cert.pem (error:02001002:system library:fopen:No such file or directory)| wsd/LOOLWSD.cpp:3343
> Cannot load CA file/directory at /etc/loolwsd/ca-chain.cert.pem (error:02001002:system library:fopen:No such file or directory)
> wsd-01186-01186 2019-07-06 17:16:20.024986 [ loolwsd ] INF  ~Admin dtor.| wsd/Admin.cpp:381
> wsd-01186-01186 2019-07-06 17:16:20.024997 [ loolwsd ] TRC  History:
> 
> { "documents" : [], "expiredDocuments" : []}
> | wsd/AdminModel.cpp:182
> wsd-01186-01186 2019-07-06 17:16:20.025006 [ loolwsd ] INF  AdminModel dtor.| wsd/AdminModel.cpp:183

**Comment by tiredofit** [comment]
Can you check to see if it does indeed exist in `/etc/loolwsd` What we might need here is to get you to set `DEBUG_MODE=TRUE` and then post the entire container startup output.

**Comment by whlsxl** [comment]
There are `loolkitconfig.xcu` and `loolwsd.xml` in `/etc/loolwsd`.
I found, I already set `- "extra_params=--o:ssl.enable=false"` in docker-compose.yml `environment`, but in `/etc/loolwsd/loolwsd.xml` , ssl is enable

>     <ssl desc="SSL settings">
>         <enable type="bool" desc="Controls whether SSL encryption is enable (do not disable for production deployment). If default is false, must first be compiled with SSL support to enable." default="true">true</enable>
>         <termination desc="Connection via proxy where loolwsd acts as working via https, but actually uses http." type="bool" default="true">false</termination>
>         <cert_file_path desc="Path to the cert file" relative="false">/etc/loolwsd/cert.pem</cert_file_path>
>         <key_file_path desc="Path to the key file" relative="false">/etc/loolwsd/key.pem</key_file_path>
>         <ca_file_path desc="Path to the ca file" relative="false">/etc/loolwsd/ca-chain.cert.pem</ca_file_path>
>         <cipher_list desc="List of OpenSSL ciphers to accept" default="ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH"></cipher_list>
>         <hpkp desc="Enable HTTP Public key pinning" enable="false" report_only="false">
>             <max_age desc="HPKP's max-age directive - time in seconds browser should remember the pins" enable="true">1000</max_age>
>             <report_uri desc="HPKP's report-uri directive - pin validation failure are reported at this URL" enable="false"></report_uri>
>             <pins desc="Base64 encoded SPKI fingerprints of keys to be pinned">
>             <pin></pin>
>             </pins>
>         </hpkp>
>     </ssl>

**Comment by whlsxl** [comment]
After I set ssl enable `false` manually,  `collabora` boot successful, but... new error...

**Comment by whlsxl** [comment]
The `extra_params` not come into effect still a problem.

**Comment by whlsxl** [comment]
Hey @tiredofit ,
I find the way to user `extra_params`, The official `Dockerfile` start loolwsd use `extra_params` as params https://github.com/CollaboraOnline/Docker-CODE/blob/master/scripts/start-libreoffice.sh#L42

**Comment by tiredofit** [comment]
Right on! I'll update this on Monday and start the build. It takes about 12 hours from my start of build to complete, will advise when a new version is posted. In the meantime if you wanted to see if it worked:

Enter in the container:
````bash
s6-svc -d /var/run/s6/services/10-loolwsd
nano /etc/s6/services/10-loolwsd/run
````

Add the extra_params part as per the official Dockerfile

Then restart the service `s6-svc -u /var/run/s6/services/10-loolwsd` - That should get you going for the time being!

**Comment by whlsxl** [comment]
Now, the `collabora` is worked, but the access through traefik is not work.
when `curl https://collabora_url` in nextcloud bash,  got `No route to host`.
Someone said this is firewall problem, still no solution.

**Comment by tiredofit** [comment]
I've got it working. I'm just building a new version of the image to set SSL parameters and will post here when ready with details and configuration.

**Comment by tiredofit** [comment]
OK. I've pushed a new version to Docker hub `tiredofit/libreoffice-online:1.5` or `latest` that will get you going on Traefik, also added a tonne more configuration options for you for the configuration file to avoid having to use the EXTRA PARAMETERS option.

Heres how to get it going via ENV Vars:

````bash
ENABLE_TLS=FALSE
ENABLE_TLS_REVERSE_PROXY=TRUE
````

In your docker-compose.yml:

````bash
    labels: 
      - traefik.enable=true
      - traefik.frontend.rule=Host:libreoffice.example.com
      - traefik.port=9980
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - traefik.backend=libreoffice-online-app
````

Let me know how you make out.
