### ISSUE TITLE
libreoffice container runs, reachable on internal network :9980, but traefik doesn't connect

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-libreoffice-online#6]
While I specified 

- traefik.port=9980

in the labels for the libreoffice machine, traefik insists on directing traffic to 
http://192.168.176.4:1025

How can it happen that traefik ignores the port definition???

**Comment by tiredofit** [comment]
That I have no idea.
Here's my labels as an example (Traefik 1.7.20, I haven't upgraded to 2.x)

````bash
      - traefik.enable=true
      - traefik.frontend.rule=Host:libreoffice.example.com
      - traefik.port=9980
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - traefik.backend=libreoffice-app
````

**Comment by joergmschulz** [comment]
this might explain why your config isn't working for me. Now I am trying 

- traefik.http.services.libreoffice.loadbalancer.server.port=9980

**Comment by tiredofit** [comment]
Not a problem. FWIW this should get you up and running immediately as a starting point:
````bash
      - ALLOWED_HOSTS=^(.*)\.domain\.org
      - ENABLE_TLS=FALSE
      - ENABLE_TLS_REVERSE_PROXY=FALSE
````

**Comment by joergmschulz** [comment]
exactly. Additionally:

hostname:  libreoffice.domain.com

and, if this domain name deviates from your nextcloud domain name, you must disable certificate checking.
Congratulations, and thank you again. 
Would it be good to add this remark to the example docker-compose.yaml? If yes, I'd create a PR.

Next, I will try to add fonts. If successful, I'll create some PRs. Also a more recent LO version is outstanding. yours crashes when filenames contain a % sign.

**Comment by tiredofit** [comment]
I'm happy to take PR's on anything! Fonts should be fairly easy, and as a hint, it happens in the 2nd stage of building the image. You'll have to experiment with the right build of LO and LOOL - it can get tricky. I spent quite a long time getting this one to work properly without falling apart. I think the biggest time suck on this is trying to clone the libreoffice repositories which takes the majority of the time. Compiling on a 16 core system goes pretty quick!

**Comment by joergmschulz** [comment]
see also activities here: https://github.com/husisusi/officeonlin-install.sh/issues/188#issuecomment-577703558

**Comment by tiredofit** [comment]
See my develop branch for latest updates - I am stalling out at the LOOL build for some unknown reason when upgrading to Node 10, Buster, and new LOOL versions. At this time its a side project to get going as current version is suiting me fine, but if you were thinking of adding to the image this is the most up to date WIP

**Comment by joergmschulz** [comment]
Studying this beast as well, I think I'll have a working compile in some days. Not only nodejs is an issue, also the compile flag --disable-werror for loleaflet.

**Comment by joergmschulz** [comment]
looks good, nearly ready to commit a pull request (just draw back one).
will start to test tonight.
+  you'll be able to select arg for version build in docker-compose.yml
+ local font directory will be pulled into build
