### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by krakazyabra** [tiredofit/docker-libreoffice-online#7]
Hi! Can you, please, update your Dockerfile to use latest versions of Libreoffice-core and Libreoffice-online? Is it possible to use collabora instead? Thanks :)

**Comment by joergmschulz** [comment]
While I don't see any issue with the current image, there is no immidiate need to change that running and well-tested version.
But, to be honest, IF I manage to get a new version up and running (I promised so in another thread and am spending some time on it currently without promising anything) - what could be YOUR contribution to that project?
